twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - Microservices
    - Spring
    - Kafka
    - ElasticSearch
  welcome-message: Hello welcome to twitter-to-kafka-service
  enable-mock-tweets: true
  min-tweet-length: 5
  max-tweet-length: 15
  mock-sleep-ms: 10000

